// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCard: typeof import("element-plus/es")["ElCard"]
    ElIcon: typeof import("element-plus/es")["ElIcon"]
    ElLink: typeof import('element-plus/es')['ElLink']
    ElSwitch: typeof import("element-plus/es")["ElSwitch"]
    MyComp: typeof import("./src/components/my-comp/index.vue")["default"]
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
  }
}
